version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dba
      POSTGRES_PASSWORD: ${SA_PASSWORD}
      POSTGRES_DB: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  api:
    build: ./backend
    container_name: api_employee
    ports:
      - "5224:5224"
    environment:
      ConnectionStrings__Postgres: "User ID=dba;Password=${SA_PASSWORD};Host=postgres;Port=5432;Database=db;Pooling=true;Connection Lifetime=0;"
      ASPNETCORE_ENVIRONMENT: Development
      Jwt__Key: 7a7b38009b94c30dd1748a438e6d85ec0624b37fd5f06379a9a3edac390bf414
      restart: on-failure
      
volumes:
  postgres_data: